language: objective-c
osx_image: xcode9.4

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=ObjectiveRocks.xcworkspace
    - IOS_FRAMEWORK_SCHEME=ObjectiveRocks-iOS
    - MACOS_FRAMEWORK_SCHEME=ObjectiveRocks
    - IOS_SDK=iphonesimulator11.0
    - MACOS_SDK=macosx10.13
  matrix:
    - DESTINATION="arch=x86_64"                                SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"                 SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"               SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"
    - DESTINATION="OS=11.0,name=iPhone X"                      SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild -quiet -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
  - travis_retry xcodebuild -quiet -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  - travis_wait 30 pod lib lint --skip-import-validation --allow-warnings
